services:
  - type: web
    name: municipal-backend
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn municipal_tax.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: municipal_tax.deployment
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_A2UaSjDFhi1f@ep-nameless-recipe-aizzuqlb-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://municipal-orpin.vercel.app
      - key: RENDER_EXTERNAL_HOSTNAME
        value: municipal-backend-3dc6.onrender.com
