# Generated by Django 4.2.28 on 2026-02-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_app', '0002_paymentrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default annual tax due amount automatically assigned when a new tax account is created', max_digits=12),
        ),
    ]
